name: test1
on:
  workflow_dispatch:
jobs:
    job1:
      runs-on: ubuntu-latest
      steps:
        - name: test variables
          run: |
            echo $CS_ENV
            CS_ENV=${CS_ENV} echo $CS_ENV
          env:
            CS_ENV: staging
            CS_ACCESS_TOKEN: test
          shell: bash
